-- Backup Full Database Schema - NewsLan
-- Generated by Antigravity
-- This schema includes all tables, constraints, extensions, RLS policies, and triggers.

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. INDEPENDENT TABLES & PARENTS
-- Profiles (Supabase Auth link)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username text UNIQUE,
  full_name text,
  avatar_url text,
  role text DEFAULT 'member'::text CHECK (role = ANY (ARRAY['guest'::text, 'member'::text, 'subscriber'::text, 'writer'::text, 'admin'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Advertisements (Parent to categories and ad_products)
CREATE TABLE IF NOT EXISTS public.advertisements (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['image'::text, 'html'::text, 'product_list'::text])),
  image_url text,
  link_url text,
  html_content text,
  placement text NOT NULL CHECK (placement = ANY (ARRAY['header_bottom'::text, 'article_before'::text, 'article_middle'::text, 'article_after'::text, 'sidebar'::text, 'section_sidebar'::text, 'feed_between'::text, 'skin_left'::text, 'skin_right'::text])),
  is_active boolean DEFAULT true,
  width integer,
  height integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Categories (Depends on advertisements for sidebar ads)
CREATE TABLE IF NOT EXISTS public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  show_on_home boolean DEFAULT true,
  display_order integer DEFAULT 0,
  bg_color text DEFAULT '#E11D48'::text,
  sidebar_ad_id uuid REFERENCES public.advertisements(id) ON DELETE SET NULL,
  sidebar_ad_2_id uuid REFERENCES public.advertisements(id) ON DELETE SET NULL,
  sidebar_ad_3_id uuid REFERENCES public.advertisements(id) ON DELETE SET NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- Product Categories
CREATE TABLE IF NOT EXISTS public.product_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  icon text NOT NULL,
  color text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Products (Depends on product_categories)
CREATE TABLE IF NOT EXISTS public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  description text,
  image_url text,
  price_range text,
  category_id uuid REFERENCES public.product_categories(id) ON DELETE SET NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- 3. DEPENDENT TABLES (CHILDREN)
-- Ad Products Junction
CREATE TABLE IF NOT EXISTS public.ad_products (
  ad_id uuid NOT NULL REFERENCES public.advertisements(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  display_order integer DEFAULT 0,
  PRIMARY KEY (ad_id, product_id)
);

-- Affiliate Links
CREATE TABLE IF NOT EXISTS public.affiliate_links (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  product_id uuid REFERENCES public.products(id) ON DELETE CASCADE,
  store_name text NOT NULL,
  url text NOT NULL,
  click_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

-- Articles
CREATE TABLE IF NOT EXISTS public.articles (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  content text NOT NULL,
  excerpt text,
  featured_image text,
  category_id uuid REFERENCES public.categories(id) ON DELETE SET NULL,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  is_premium boolean DEFAULT false,
  is_published boolean DEFAULT false,
  is_breaking boolean DEFAULT false,
  views_count integer DEFAULT 0,
  seo_title text,
  seo_description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  source_url text,
  product_placement character varying DEFAULT 'after'::character varying CHECK (product_placement::text = ANY (ARRAY['middle'::character varying, 'after'::character varying]::text[])),
  focus_keyword text
);

-- Article Products Junction
CREATE TABLE IF NOT EXISTS public.article_products (
  article_id uuid NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  PRIMARY KEY (article_id, product_id)
);

-- AI Auto Jobs
CREATE TABLE IF NOT EXISTS public.ai_auto_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name character varying NOT NULL,
  task_key character varying NOT NULL UNIQUE,
  theme text NOT NULL,
  category_id uuid REFERENCES public.categories(id) ON DELETE SET NULL,
  style character varying DEFAULT 'Formal'::character varying,
  model_type character varying DEFAULT 'Breaking News'::character varying,
  generate_image boolean DEFAULT true,
  is_published boolean DEFAULT true,
  is_active boolean DEFAULT true,
  last_run_at timestamp without time zone,
  last_run_status character varying,
  total_runs integer DEFAULT 0,
  total_articles_generated integer DEFAULT 0,
  articles_per_run integer DEFAULT 1,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  target_language text DEFAULT 'id'::text
);

-- RSS Auto Jobs
CREATE TABLE IF NOT EXISTS public.rss_auto_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name character varying NOT NULL,
  task_key character varying NOT NULL UNIQUE,
  rss_url text NOT NULL,
  category_id uuid REFERENCES public.categories(id) ON DELETE SET NULL,
  is_published boolean DEFAULT true,
  max_articles_per_run integer DEFAULT 3,
  is_active boolean DEFAULT true,
  last_run_at timestamp without time zone,
  last_run_status character varying,
  last_run_articles integer DEFAULT 0,
  total_runs integer DEFAULT 0,
  total_articles_published integer DEFAULT 0,
  show_source_attribution boolean DEFAULT true,
  use_ai_image boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  target_language text DEFAULT 'id'::text,
  writing_style character varying DEFAULT 'Professional'::character varying,
  article_model character varying DEFAULT 'Straight News'::character varying,
  job_type character varying DEFAULT 'standard'::character varying,
  search_keyword text,
  trend_region text DEFAULT 'local'::text,
  trend_niche text DEFAULT 'any'::text,
  thumbnail_priority text DEFAULT 'ai_priority'::text
);

-- Analytics Events
CREATE TABLE IF NOT EXISTS public.analytics_events (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  event_type text NOT NULL,
  target_id uuid NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now()
);

-- Complaints
CREATE TABLE IF NOT EXISTS public.complaints (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text NOT NULL,
  image_url text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'resolved'::text, 'rejected'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Shorts
CREATE TABLE IF NOT EXISTS public.shorts (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title text,
  video_url text NOT NULL,
  thumbnail_url text,
  views_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

-- Short Products Junction
CREATE TABLE IF NOT EXISTS public.short_products (
  short_id uuid NOT NULL REFERENCES public.shorts(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  PRIMARY KEY (short_id, product_id)
);

-- WP Import Log
CREATE TABLE IF NOT EXISTS public.wp_import_log (
  wp_post_id integer NOT NULL PRIMARY KEY,
  article_id uuid REFERENCES public.articles(id) ON DELETE CASCADE,
  imported_at timestamp with time zone DEFAULT now()
);

-- 4. OTHER MISC TABLES
-- Banners
CREATE TABLE IF NOT EXISTS public.banners (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title text,
  image_url text NOT NULL,
  link_url text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Navigation Links
CREATE TABLE IF NOT EXISTS public.navigation_links (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  label text NOT NULL,
  url text NOT NULL,
  icon text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  location text DEFAULT 'main'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Pages (Supports static pages like About, Privacy)
CREATE TABLE IF NOT EXISTS public.pages (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  content text NOT NULL,
  is_published boolean DEFAULT true,
  is_footer boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Site Settings
CREATE TABLE IF NOT EXISTS public.site_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  setting_key text NOT NULL UNIQUE,
  setting_value text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);


-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shorts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.short_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wp_import_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.advertisements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ad_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_auto_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rss_auto_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.navigation_links ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Categories Policies
CREATE POLICY "Categories are viewable by everyone" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Admins can manage categories" ON public.categories FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Articles Policies
CREATE POLICY "Published non-premium articles are viewable by everyone" ON public.articles FOR SELECT USING (is_published = true AND is_premium = false);
CREATE POLICY "Premium articles are viewable by subscribers and admins" ON public.articles FOR SELECT USING (
  is_published = true AND is_premium = true AND (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('subscriber', 'admin'))
  )
);
CREATE POLICY "Writers can manage their own articles" ON public.articles FOR ALL USING (author_id = auth.uid());
CREATE POLICY "Admins can manage all articles" ON public.articles FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- Products & Affiliate Links
CREATE POLICY "Products and links are viewable by everyone" ON public.products FOR SELECT USING (true);
CREATE POLICY "Admins can manage products" ON public.products FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Affiliate links are viewable by everyone" ON public.affiliate_links FOR SELECT USING (true);
CREATE POLICY "Admins can manage affiliate links" ON public.affiliate_links FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- Video Shorts
CREATE POLICY "Shorts are viewable by everyone" ON public.shorts FOR SELECT USING (true);
CREATE POLICY "Admins can manage shorts" ON public.shorts FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Short products are viewable by everyone" ON public.short_products FOR SELECT USING (true);
CREATE POLICY "Admins can manage short products" ON public.short_products FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- Article Products
CREATE POLICY "Article products are viewable by everyone" ON public.article_products FOR SELECT USING (true);
CREATE POLICY "Admins can manage article products" ON public.article_products FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- Advertisements & Banners
CREATE POLICY "Ads are viewable by everyone" ON public.advertisements FOR SELECT USING (true);
CREATE POLICY "Admins can manage ads" ON public.advertisements FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Ad products are viewable by everyone" ON public.ad_products FOR SELECT USING (true);
CREATE POLICY "Admins can manage ad products" ON public.ad_products FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Banners are viewable by everyone" ON public.banners FOR SELECT USING (is_active = true);
CREATE POLICY "Admins can manage banners" ON public.banners FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Site Settings & Pages
CREATE POLICY "Allow public read for site_settings" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Allow authenticated update for site_settings" ON public.site_settings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow public read access to published pages" ON public.pages FOR SELECT USING (is_published = true);
CREATE POLICY "Allow authenticated users full access to pages" ON public.pages FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Complaints
CREATE POLICY "Users can insert their own complaints" ON public.complaints FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view their own complaints" ON public.complaints FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all complaints" ON public.complaints FOR SELECT USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Admins can update complaint status" ON public.complaints FOR UPDATE USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- AI & RSS Jobs
CREATE POLICY "Allow authenticated users to manage AI jobs" ON public.ai_auto_jobs FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public to read active AI jobs by task_key" ON public.ai_auto_jobs FOR SELECT TO public USING (is_active = true);
CREATE POLICY "Allow authenticated users to view RSS jobs" ON public.rss_auto_jobs FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated users to insert RSS jobs" ON public.rss_auto_jobs FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated users to update RSS jobs" ON public.rss_auto_jobs FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated users to delete RSS jobs" ON public.rss_auto_jobs FOR DELETE TO authenticated USING (true);
CREATE POLICY "Allow public to read active jobs by task_key" ON public.rss_auto_jobs FOR SELECT TO public USING (is_active = true);

-- Product Categories
CREATE POLICY "Allow public read access for product_categories" ON public.product_categories FOR SELECT USING (true);
CREATE POLICY "Allow full access for authenticated users on product_categories" ON public.product_categories FOR ALL USING (auth.role() = 'authenticated');

-- 6. FUNCTIONS & TRIGGERS
-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 'member');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
